services:
  - type: static_site
    name: antrei-frontend
    plan: free
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: VITE_API_URL
        sync: false
    buildFilter:
      paths:
        - src: antrein-mvp/antrein-frontend
          ignore: false
