-- AntreIn Supabase schema and RLS policies
-- Run in Supabase SQL Editor. This is written for the current frontend code.
-- If your tables already exist, compare the column names first before running
-- the CREATE TABLE section.

create extension if not exists pgcrypto;

-- =========================================================
-- 1. Tables
-- =========================================================

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  organization text not null default '',
  phone text not null default '',
  role text not null default 'organizer',
  initials text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  name text not null default '',
  organization text not null default '',
  phone text not null default '',
  role text not null default 'organizer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_point_configs (
  user_id uuid primary key references auth.users(id) on delete cascade,
  identifier text not null default '1',
  label text not null default 'Loket',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep existing projects compatible if these tables were created before the
-- profile fields were finalized.
alter table public.users add column if not exists email text not null default '';
alter table public.users add column if not exists name text not null default '';
alter table public.users add column if not exists organization text not null default '';
alter table public.users add column if not exists phone text not null default '';
alter table public.users add column if not exists role text not null default 'organizer';
alter table public.users add column if not exists initials text not null default '';
alter table public.users add column if not exists created_at timestamptz not null default now();
alter table public.users add column if not exists updated_at timestamptz not null default now();

alter table public.organizations add column if not exists email text not null default '';
alter table public.organizations add column if not exists name text not null default '';
alter table public.organizations add column if not exists organization text not null default '';
alter table public.organizations add column if not exists phone text not null default '';
alter table public.organizations add column if not exists role text not null default 'organizer';
alter table public.organizations add column if not exists created_at timestamptz not null default now();
alter table public.organizations add column if not exists updated_at timestamptz not null default now();

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null default '',
  date date not null,
  status text not null default 'draft' check (status in ('draft', 'live', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  name text not null,
  prefix text not null,
  quota_type text not null default 'unlimited' check (quota_type in ('unlimited', 'limited')),
  quota_limit integer,
  count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.queues (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  current_number integer not null default 0,
  total_waiting integer not null default 0,
  status text not null default 'idle' check (status in ('idle', 'serving', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (service_id)
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  number integer not null,
  uuid text not null unique,
  created_at timestamptz not null default now(),
  unique (event_id, service_id, number)
);

create index if not exists events_organizer_id_idx on public.events(organizer_id);
create index if not exists services_event_id_idx on public.services(event_id);
create index if not exists queues_event_id_idx on public.queues(event_id);
create index if not exists queues_service_id_idx on public.queues(service_id);
create index if not exists tickets_event_service_idx on public.tickets(event_id, service_id);
create index if not exists tickets_uuid_idx on public.tickets(uuid);

-- =========================================================
-- 2. Grants
-- =========================================================

grant usage on schema public to anon, authenticated;

grant select on public.events, public.services, public.queues to anon, authenticated;
grant select, insert on public.tickets to anon, authenticated;
grant update (total_waiting) on public.queues to anon;

grant select, insert, update, delete on
  public.users,
  public.organizations,
  public.service_point_configs,
  public.events,
  public.services,
  public.queues,
  public.tickets
to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- =========================================================
-- 3. Enable RLS
-- =========================================================

alter table public.users enable row level security;
alter table public.organizations enable row level security;
alter table public.service_point_configs enable row level security;
alter table public.events enable row level security;
alter table public.services enable row level security;
alter table public.queues enable row level security;
alter table public.tickets enable row level security;

-- =========================================================
-- 4. Drop old policies
-- =========================================================

drop policy if exists "users_select_own" on public.users;
drop policy if exists "users_insert_own" on public.users;
drop policy if exists "users_update_own" on public.users;

drop policy if exists "organizations_select_own" on public.organizations;
drop policy if exists "organizations_insert_own" on public.organizations;
drop policy if exists "organizations_update_own" on public.organizations;

drop policy if exists "service_point_configs_select_own" on public.service_point_configs;
drop policy if exists "service_point_configs_insert_own" on public.service_point_configs;
drop policy if exists "service_point_configs_update_own" on public.service_point_configs;

drop policy if exists "events_select_owner" on public.events;
drop policy if exists "events_select_public_live" on public.events;
drop policy if exists "events_insert_owner" on public.events;
drop policy if exists "events_update_owner" on public.events;
drop policy if exists "events_delete_owner" on public.events;

drop policy if exists "services_select_owner" on public.services;
drop policy if exists "services_select_public_live" on public.services;
drop policy if exists "services_insert_owner" on public.services;
drop policy if exists "services_update_owner" on public.services;
drop policy if exists "services_delete_owner" on public.services;

drop policy if exists "queues_select_owner" on public.queues;
drop policy if exists "queues_select_public_live" on public.queues;
drop policy if exists "queues_insert_owner" on public.queues;
drop policy if exists "queues_update_owner" on public.queues;
drop policy if exists "queues_update_public_waiting" on public.queues;
drop policy if exists "queues_delete_owner" on public.queues;

drop policy if exists "tickets_select_owner" on public.tickets;
drop policy if exists "tickets_select_public_current_app" on public.tickets;
drop policy if exists "tickets_insert_public_live" on public.tickets;
drop policy if exists "tickets_delete_owner" on public.tickets;

-- =========================================================
-- 5. Profile/account policies
-- =========================================================

create policy "users_select_own"
on public.users for select
to authenticated
using (id = auth.uid());

create policy "users_insert_own"
on public.users for insert
to authenticated
with check (id = auth.uid());

create policy "users_update_own"
on public.users for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "organizations_select_own"
on public.organizations for select
to authenticated
using (id = auth.uid());

create policy "organizations_insert_own"
on public.organizations for insert
to authenticated
with check (id = auth.uid());

create policy "organizations_update_own"
on public.organizations for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "service_point_configs_select_own"
on public.service_point_configs for select
to authenticated
using (user_id = auth.uid());

create policy "service_point_configs_insert_own"
on public.service_point_configs for insert
to authenticated
with check (user_id = auth.uid());

create policy "service_point_configs_update_own"
on public.service_point_configs for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- =========================================================
-- 6. Organizer event policies
-- =========================================================

create policy "events_select_owner"
on public.events for select
to authenticated
using (organizer_id = auth.uid());

create policy "events_select_public_live"
on public.events for select
to anon, authenticated
using (status = 'live');

create policy "events_insert_owner"
on public.events for insert
to authenticated
with check (organizer_id = auth.uid());

create policy "events_update_owner"
on public.events for update
to authenticated
using (organizer_id = auth.uid())
with check (organizer_id = auth.uid());

create policy "events_delete_owner"
on public.events for delete
to authenticated
using (organizer_id = auth.uid());

create policy "services_select_owner"
on public.services for select
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "services_select_public_live"
on public.services for select
to anon, authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.status = 'live'
  )
);

create policy "services_insert_owner"
on public.services for insert
to authenticated
with check (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "services_update_owner"
on public.services for update
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.organizer_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "services_delete_owner"
on public.services for delete
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = services.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "queues_select_owner"
on public.queues for select
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "queues_select_public_live"
on public.queues for select
to anon, authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.status = 'live'
  )
);

create policy "queues_insert_owner"
on public.queues for insert
to authenticated
with check (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.organizer_id = auth.uid()
  )
);

create policy "queues_update_owner"
on public.queues for update
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.organizer_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.organizer_id = auth.uid()
  )
);

-- Needed by the current public takeTicket() frontend flow, which increments
-- queues.total_waiting from an unauthenticated page.
create policy "queues_update_public_waiting"
on public.queues for update
to anon
using (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.status = 'live'
  )
)
with check (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.status = 'live'
  )
);

create policy "queues_delete_owner"
on public.queues for delete
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = queues.event_id
      and e.organizer_id = auth.uid()
  )
);

-- =========================================================
-- 7. Ticket policies
-- =========================================================

create policy "tickets_select_owner"
on public.tickets for select
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = tickets.event_id
      and e.organizer_id = auth.uid()
  )
);

-- The current frontend loads /ticket/:ticketUuid directly from public.tickets.
-- RLS cannot verify that a request includes the uuid filter, so this is broad.
-- For stricter security, replace loadPublicTicket() with a SECURITY DEFINER RPC.
create policy "tickets_select_public_current_app"
on public.tickets for select
to anon
using (true);

create policy "tickets_insert_public_live"
on public.tickets for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.events e
    join public.services s on s.event_id = e.id
    where e.id = tickets.event_id
      and s.id = tickets.service_id
      and e.status = 'live'
  )
);

create policy "tickets_delete_owner"
on public.tickets for delete
to authenticated
using (
  exists (
    select 1
    from public.events e
    where e.id = tickets.event_id
      and e.organizer_id = auth.uid()
  )
);

-- =========================================================
-- 8. Recommended registration bootstrap
-- =========================================================
-- Frontend register sends these values:
--   auth.users.email                  = login email
--   auth.users.encrypted_password     = login password, managed by Supabase Auth
--   raw_user_meta_data->>'name'       = user's full name
--   raw_user_meta_data->>'organization' = organization name
--   raw_user_meta_data->>'phone'      = user's phone number
--
-- Password is never stored in public tables. Public tables only store profile
-- data that the app needs after login.
--
-- This trigger keeps registration safe when email confirmation is enabled:
-- the database creates the profile with SECURITY DEFINER instead of relying on
-- an authenticated browser session immediately after signUp.

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_email text := coalesce(new.email, '');
  profile_name text := coalesce(
    nullif(new.raw_user_meta_data->>'name', ''),
    split_part(coalesce(new.email, ''), '@', 1)
  );
  profile_organization text := coalesce(new.raw_user_meta_data->>'organization', '');
  profile_phone text := coalesce(new.raw_user_meta_data->>'phone', '');
begin
  insert into public.users (id, email, name, organization, role, initials, phone)
  values (
    new.id,
    profile_email,
    profile_name,
    profile_organization,
    'organizer',
    upper(left(profile_name, 2)),
    profile_phone
  )
  on conflict (id) do update set
    email = excluded.email,
    name = excluded.name,
    organization = excluded.organization,
    role = excluded.role,
    initials = excluded.initials,
    phone = excluded.phone,
    updated_at = now();

  insert into public.organizations (id, email, name, organization, role, phone)
  values (
    new.id,
    profile_email,
    profile_name,
    profile_organization,
    'organizer',
    profile_phone
  )
  on conflict (id) do update set
    email = excluded.email,
    name = excluded.name,
    organization = excluded.organization,
    role = excluded.role,
    phone = excluded.phone,
    updated_at = now();

  insert into public.service_point_configs (user_id, identifier, label)
  values (new.id, '1', 'Loket')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();
